### ISSUE TITLE
git clone git@github.com:vFabric/springtrader.git doesn't work on Mac or Centos

### ISSUE THREAD

**Issue by ghost** [vmware-archive/springtrader#40]
"git clone git@github.com:vFabric/springtrader.git" doesn't work on Mac or Centos for me, had to do "git clone git://github.com/vFabric/springtrader.git"

I get the following:
dbeauregard-mbp:Downloads dbeauregard$ git clone git@github.com:vFabric/springtrader.git
Cloning into 'springtrader'...
Permission denied (publickey).
fatal: The remote end hung up unexpectedly

**Comment by dussab** [comment]
Hi,
I just tested "git clone git@github.com:vFabric/springtrader.git" on the mac and it seems to work fine for me. Did you happen to setup your ssh keys under your profile? If not, here are the instructions: https://help.github.com/articles/generating-ssh-keys

Let me know if that solves the issue.
Brian

**Comment by ghost** [comment]
Hi Brian,
For trying out spring trader I was just hoping to use the anonymous read only access which does seem to work with this "git clone git://github.com/vFabric/springtrader.git".  IMHO you might consider adding the link to the ssh keys to the user guide or alternatively just listing the read only uri.

-Derek
